name: Deno
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task test
      - run: deno task lcov
      - uses: hrishikesh-kadam/setup-lcov@v1
      - uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: cov_profile/cov.lcov
          minimum-coverage: 60
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
